### ISSUE TITLE
User input malformed: expected str for dictionary value @ data['arm_code']

### ISSUE THREAD

**Issue by BinaryShrub** [uvjustin/alarmdotcom#86]
I'm getting this error on v2 when trying to set silent arming for arm stay:
```
User input malformed: expected str for dictionary value @ data['arm_code']
```

Does this mean I have to provide a code? in v1 I was able to do silent arming without a code provided.

![image](https://user-images.githubusercontent.com/10691501/153129348-a10ae444-2258-4a44-8c95-9b0061222c30.png)

**Comment by BinaryShrub** [comment]
Also now that I have a code set, I cannot clear it.

**Comment by elahd** [comment]
Would you mind copying and pasting the configuration.yaml settings you had set before migrating? Sensitive info redacted, of course. I'm looking for the exact values you had set for force bypass, silent arming, and no entry delay.

**Comment by BinaryShrub** [comment]
```
# Alarm.com
# https://github.com/uvjustin/alarmdotcom
alarm_control_panel:
  - platform: alarmdotcom
    username: !secret alarmdotcom_username
    password: !secret alarmdotcom_password
    silent_arming: "true"
    two_factor_cookie: !secret alarmdotcom_2fa
```

**Comment by elahd** [comment]
Did you have any other options set there, like an arming code?

Also, it would be helpful if you could provide more detailed errors. If you add this to configuration.yaml and restart HA, you'll see debug-level errors for the integration in the Home Assistant debug log:

```yaml
logger:
  default: warn
  logs:
    custom_components.alarmdotcom: debug
    pyalarmdotcomajax: debug
```

**Comment by elahd** [comment]
This should be fixed in v0.2.0-beta.10. Can you update and confirm?

**Comment by BinaryShrub** [comment]
I am still getting the error. I think the actual cause is that I want to leave the arm code blank, I dont wanna set it. And without setting it you are trying to retrieve the value that doesnt exist?

Seems like the fix would be if the string is empty, dont set it?

**Comment by elahd** [comment]
Got it. Home Assistant doesn't make it easy to let users delete data from fields that are pre-populated with the current value. (It interprets _blank_ as _no change_ instead of _empty_.) Try v0.2.0-beta.11. I added a separate checkbox that turns the security code on and off. You still won't be able to clear the security code field, but you will be able to tell the integration to ignore it.
